site_name: WouaMatrimony-Doc

# Meta tags (placed in header)
site_description: 
site_author: Woualabs
site_url: https://woualabs.github.io/Wouamatrimony-Docs/

# Repository (add link to repository on each page)
repo_name: WouaMatrimony-Doc
repo_url: https://woualabs.github.io/Wouamatrimony-Docs
edit_uri: edit/master/src/doc/docs/

#Copyright (shown at the footer)
copyright: 'Copyright &copy; 2021 Woualabs'

# Meterial theme
theme:
  name: 'material'
  favicon: assets/logo.png
  logo: assets/logo.png
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
  palette:
    primary: blue
    accent: pink
  social:
    - type: 'github'
    - link: 'https://github.com/Woualabs/WouaMatrimonyKMP'

#plugins:
#  - search
#    Required for variables support (https://github.com/rosscdh/mkdocs-markdownextradata-plugin)
#  - markdownextradata

#extra:
#  palette:
#    primary: 'indigo'
#    accent: 'indigo'

#  social:
#    - icon: fontawesome/brands/github
#      link: https://github.com/you
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/you


# Google Analytics
#google_analytics:
#  - 'UA-111111111-1'
#  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - def_list
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - attr_list
# Dev server binding
#dev_addr: 127.0.0.1:3001

nav:
  - 'Overview': index.md
  - 'Changelog': changelog.md
  - 'Code of Conduct': code_of_conduct.md

  - IOS:
      - 'Getting Started': ios/started/gettingStarted.md
      - 'Guides':
          - 'User OnBoard': ios/guides/userOnboard.md
          - 'User Access': ios/guides/userAccess.md
          - 'Plan': ios/guides/plan.md
          - 'Notification': ios/guides/notification.md

  - Android:
      - 'Getting Started': android/started/gettingStarted.md
      - 'Guides':
          - 'User OnBoard': android/guides/userOnboard.md
          - 'User Access': android/guides/userAccess.md
          - 'Plan': android/guides/plan.md
          - 'Notification': android/guides/notification.md

  - JavaScript:
      - Dealer:
          - 'Getting Started': javascript/dealer/started/gettingStarted.md
          - 'Guides':
              - 'User OnBoard': javascript/dealer/guides/userOnboard.md
              - 'User Access': javascript/dealer/guides/userAccess.md
              - 'Plan': javascript/dealer/guides/plan.md
              - 'Notification': javascript/dealer/guides/notification.md

      - Customer:
          - 'Getting Started': javascript/customer/started/gettingStarted.md
          - 'Guides':
              - 'User OnBoard': javascript/customer/guides/userOnboard.md
              - 'User Access': javascript/customer/guides/userAccess.md
              - 'Plan': javascript/customer/guides/plan.md
              - 'Notification': javascript/customer/guides/notification.md

  - About:
      - 'Release notes': about/history.md