name: Build and deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Wouamatrimony-Docs
        uses: actions/checkout@v2
        with:
          path: Wouamatrimony-Docs

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            docs_changed:
              - 'docs/**'
          working-directory: ./dokka

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Get current Wouamatrimony version
        run: echo "WOUAMATRIMONY_VERSION=`./gradlew :properties | grep '^version:.*' | cut -d ' ' -f 2 | cut -d '-' -f 1`" >> $GITHUB_ENV
        if: steps.filter.outputs.docs_changed == 'true'
        working-directory: ./Wouamatrimony-Docs

      - name: Build docs
        run: ./gradlew mkdocsBuild -PWouamatrimony_version=$Wouamatrimony_VERSION --info
        if: steps.filter.outputs.docs_changed == 'true'
        working-directory: ./Wouamatrimony-Docs

      - name: Deploy
        uses: woualabs/git_pages
        if: steps.filter.outputs.docs_changed == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./WouaMatrimony-Docs/docs/build/mkdocs
          keep_files: true
          full_commit_message: Publish ${{ env.WOUAMATRIMONY_VERSION }} documentation
