name: Publish the mkdocs to gh-pages

on:
  push:
    branches:
      - kalaivanan/docs

jobs:
  deploy-website:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Wouamatrimony-Docs
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Prep mkdocs
        run: .github/workflows/prepare_mkdocs.sh

#      - name: Get current Wouamatrimony version
#          run: echo "WOUAMATRIMONY_VERSION=`./gradlew :properties | grep '^version:.*' | cut -d ' ' -f 2 | cut -d '-' -f 1`" >> $GITHUB_ENV

      - name: Build mkdocs
        run: |
          pip install -r requirements.txt
          mkdocs build

      - name: Deploy 🚀
        if: success()
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: site # The folder the action should deploy.
          SINGLE_COMMIT: true

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=true -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
